name: Destroy review application on Amazon Elastic Beanstalk

on:
  pull_request:
    types: [closed, unlabeled]

jobs:
  terraform-destroy:
    name: Destroy
    runs-on: ubuntu-latest
    env:
      KEY_PREFIX_NAME: ${{ github.event.repository.name }}
      KEY_NAME: ${{ github.event.number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Adapt AWS Terraform Backend
        id: aws-backend-write
        run: |
          cd ./terraform
          sed -i -e "s/__KEY_PREFIX_NAME__/$KEY_PREFIX_NAME/g" ./aws.tf
          sed -i -e "s/__KEY_NAME__/$KEY_NAME/g" ./aws.tf
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform
        env:
          TF_WORKSPACE: ${{ github.event.repository.name }}-pr-${{ github.event.number }}

      - name: Terraform Destroy
        id: Destroy
        if: github.event_name == 'pull_request'
        run: terraform apply -destroy -auto-approve -var 'name=${{ github.event.repository.name }}' -var 'stage=pr-${{ github.event.number }}' -var 'branch=${{ github.head_ref }}'
        working-directory: terraform
        env:
          TF_WORKSPACE: ${{ github.event.repository.name }}
